In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('Netflix_Titles.csv')

In [4]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [80]:
df2 = df.drop(['date_added'],axis='columns')

In [81]:
df2.sample(5)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description
1497,s1498,Movie,"Hello, Love, Goodbye",Cathy Garcia-Molina,"Kathryn Bernardo, Alden Richards, Maymay Entra...",Philippines,2019,TV-14,117 min,"Dramas, International Movies, Romantic Movies","In Hong Kong, the lives of two overseas Filipi..."
911,s912,TV Show,Sab Jholmaal Hai,Vijay Roche,NaN,India,2017,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","In this madcap comedy, two mischievous cats, a..."
7835,s7836,TV Show,Razia Sultan,NaN,"Pankhuri Awasthy, Saurabh Pandey, Rohit Purohi...",India,2015,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ...",This sweeping historical drama charts the rise...
6008,s6009,Movie,3 Generations,Gaby Dellal,"Elle Fanning, Naomi Watts, Susan Sarandon, Tat...",United States,2015,PG-13,92 min,"Dramas, LGBTQ Movies",When teenage Ray begins transitioning from fem...
6015,s6016,Movie,4th Man Out,Andrew Nackman,"Evan Todd, Parker Young, Chord Overstreet, Jon...",United States,2015,NR,86 min,"Comedies, LGBTQ Movies",A young mechanic comes out to his extremely st...

In [82]:
df2['title'] = df2['title'].fillna('other')

In [83]:
df2['director'] = df2['director'].fillna('other')
df2['cast'] = df2['cast'].fillna('other')
df2['country'] = df2['country'].fillna('other')
df2['director'] = df2['director'].fillna('other')

In [84]:
df2['rating'] = df2['rating'].fillna('other')

In [85]:
df2['duration'] = df2['duration'].fillna('other')

In [86]:
df2.head(1)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,other,United States,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."

In [91]:
def remove_space(L):
    L1 = L.split(" ")
    return "".join(L1)

In [95]:
df2['type'] = df2['type'].apply(remove_space)
df2['director'] = df2['director'].apply(remove_space)
df2['country'] = df2['country'].apply(remove_space)
df2['duration'] = df2['duration'].apply(remove_space)
df2['listed_in'] = df2['listed_in'].apply(remove_space)

In [96]:
df2

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,KirstenJohnson,other,UnitedStates,2020,PG-13,90min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TVShow,Blood & Water,other,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",SouthAfrica,2021,TV-MA,2Seasons,"InternationalTVShows,TVDramas,TVMysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TVShow,Ganglands,JulienLeclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",other,2021,TV-MA,1Season,"CrimeTVShows,InternationalTVShows,TVAction&Adv...",To protect his family from a powerful drug lor...
3,s4,TVShow,Jailbirds New Orleans,other,other,other,2021,TV-MA,1Season,"Docuseries,RealityTV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TVShow,Kota Factory,other,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,TV-MA,2Seasons,"InternationalTVShows,RomanticTVShows,TVComedies",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,DavidFincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",UnitedStates,2007,R,158min,"CultMovies,Dramas,Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TVShow,Zombie Dumb,other,other,other,2018,TV-Y7,2Seasons,"Kids'TV,KoreanTVShows,TVComedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,RubenFleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",UnitedStates,2009,R,88min,"Comedies,HorrorMovies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,PeterHewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",UnitedStates,2006,PG,88min,"Children&FamilyMovies,Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,MozezSingh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2015,TV-14,111min,"Dramas,InternationalMovies,Music&Musicals",A scrappy but poor boy worms his way into a ty...

In [97]:
df2['release_year'] = df2["release_year"].map(str)

In [99]:
df2['tags'] = df2['type']+ ','+df2['director']+ ','+df2['cast']+ ','+df2['country']+ ','+df2['release_year']+ ','+df2['rating']+ ','+df2['duration']+ ','+df2['listed_in']
df2.sample(4)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,tags
665,s666,TVShow,Deadwind,other,"Pihla Viitala, Lauri Tilkanen, Jani Volanen, T...","Finland,Germany",2020,TV-MA,2Seasons,"CrimeTVShows,InternationalTVShows,TVDramas","Just months after a tragic loss, detective Sof...","TVShow,other,Pihla Viitala, Lauri Tilkanen, Ja..."
71,s72,Movie,A StoryBots Space Adventure,DavidA.Vargas,"Evan Spiridellis, Erin Fitzgerald, Jeff Gill, ...",other,2021,TV-Y,13min,Children&FamilyMovies,Join the StoryBots and the space travelers of ...,"Movie,DavidA.Vargas,Evan Spiridellis, Erin Fit..."
281,s282,Movie,Brother Jekwu,CharlesUwagbai,"Mike Ezuruonye, Juliet Ochienge, Angela Okorie...",Nigeria,2016,TV-14,101min,"Comedies,InternationalMovies","Chasing wild success, a village hustler follow...","Movie,CharlesUwagbai,Mike Ezuruonye, Juliet Oc..."
3986,s3987,TVShow,The OA,other,"Brit Marling, Jason Isaacs, Emory Cohen, Scott...",UnitedStates,2019,TV-MA,2Seasons,"TVDramas,TVMysteries,TVSci-Fi&Fantasy","Seven years after vanishing from her home, a y...","TVShow,other,Brit Marling, Jason Isaacs, Emory..."

In [102]:
new = df2[['show_id','title','tags']]

In [103]:
new.head(5)

,show_id,title,tags
0,s1,Dick Johnson Is Dead,"Movie,KirstenJohnson,other,UnitedStates,2020,P..."
1,s2,Blood & Water,"TVShow,other,Ama Qamata, Khosi Ngema, Gail Mab..."
2,s3,Ganglands,"TVShow,JulienLeclercq,Sami Bouajila, Tracy Got..."
3,s4,Jailbirds New Orleans,"TVShow,other,other,other,2021,TV-MA,1Season,Do..."
4,s5,Kota Factory,"TVShow,other,Mayur More, Jitendra Kumar, Ranja..."

In [109]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 8007,
                    stop_words = 'english')

In [110]:
vector = cv.fit_transform(new['tags']).toarray()

In [111]:
vector.shape

(8807, 8007)

In [112]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [119]:
similarity

array([[1.        , 0.        , 0.        , ..., 0.17342199, 0.22237479,
        0.08451543],
       [0.        , 1.        , 0.28867513, ..., 0.        , 0.        ,
        0.05      ],
       [0.        , 0.28867513, 1.        , ..., 0.        , 0.        ,
        0.05773503],
       ...,
       [0.17342199, 0.        , 0.        , ..., 1.        , 0.22496064,
        0.05129892],
       [0.22237479, 0.        , 0.        , ..., 0.22496064, 1.        ,
        0.0438529 ],
       [0.08451543, 0.05      , 0.05773503, ..., 0.05129892, 0.0438529 ,
        1.        ]])

In [132]:
def recommend(movie):
    index = new[new['title'] == movie].index
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(f'{i} movie is',endl="")
        print(new.iloc[i[0]].title)

In [134]:
recommend('Ganglands')